name: delta_services
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  flutter_neumorphic_null_safety: ^3.2.0
  event_bus: ^2.0.0
  get_it: ^7.0.0
  simple_animations: ^3.1.1
  spaces: ^0.5.0
  layoutr: ^1.0.0
  expandable: ^5.0.1
  badges: ^2.0.0-nullsafety.1
  responsive_grid: ^2.0.0
  bubble_tab_indicator: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/json/
  fonts:
    - family:  SakwahIcons
      fonts:
        - asset: assets/font/SakwahIcons.ttf

flutter_gen:
  output: lib/assets/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml
